CREATE DATABASE IF NOT EXISTS guajira_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE guajira_platform;

CREATE TABLE IF NOT EXISTS admin (
  id_admin INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rol (
  id_rol INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tipo_producto (
  id_tipo_producto INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS departamento (
  id_departamento INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS municipio (
  id_municipio INT AUTO_INCREMENT PRIMARY KEY,
  id_departamento INT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_municipio_departamento
    FOREIGN KEY (id_departamento) REFERENCES departamento(id_departamento)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  UNIQUE KEY uq_municipio_dep (id_departamento, nombre)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comunidad (
  id_comunidad INT AUTO_INCREMENT PRIMARY KEY,
  id_municipio INT NOT NULL,
  nombre TEXT NOT NULL,
  logo_dir TEXT NULL,
  descripcion TEXT NULL,
  direccion TEXT NULL,
  coordenadas TEXT NULL,
  numero_contacto TEXT NULL,
  visibilidad TINYINT(1) NOT NULL DEFAULT 1,
  fecha_fundacion DATE NULL,
  fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_comunidad_municipio
    FOREIGN KEY (id_municipio) REFERENCES municipio(id_municipio)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS miembro (
  id_miembro INT AUTO_INCREMENT PRIMARY KEY,
  id_comunidad INT NOT NULL,
  rol_id INT NOT NULL,
  cedula INT NOT NULL UNIQUE,
  nombres TEXT NOT NULL,
  fecha_nacimiento DATE NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'activo',
  genero VARCHAR(50) NULL,
  numero_contacto VARCHAR(20) NULL,
  fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_miembro_comunidad
    FOREIGN KEY (id_comunidad) REFERENCES comunidad(id_comunidad)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_miembro_rol
    FOREIGN KEY (rol_id) REFERENCES rol(id_rol)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS producto (
  id_producto INT AUTO_INCREMENT PRIMARY KEY,
  id_miembro INT NOT NULL,
  id_tipo_producto INT NOT NULL,
  nombre TEXT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  descripcion TEXT NULL,
  visibilidad TINYINT(1) NOT NULL DEFAULT 1,
  fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_producto_miembro
    FOREIGN KEY (id_miembro) REFERENCES miembro(id_miembro)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_producto_tipo
    FOREIGN KEY (id_tipo_producto) REFERENCES tipo_producto(id_tipo_producto)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categoria_turistica (
  id_categoria_turistica CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  nombre TEXT NOT NULL,
  icono_dir TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS post (
  id_post CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  id_miembro INT NOT NULL,
  descripcion TEXT NOT NULL,
  visibilidad TINYINT(1) NOT NULL DEFAULT 1,
  likes INT NOT NULL DEFAULT 0,
  fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_miembro
    FOREIGN KEY (id_miembro) REFERENCES miembro(id_miembro)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS post_media (
  id_post_media CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  id_post CHAR(36) NOT NULL,
  media_dir TEXT NOT NULL,
  `index` INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_media_post
    FOREIGN KEY (id_post) REFERENCES post(id_post)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS producto_media (
  id_producto_media CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  id_producto INT NOT NULL,
  media_dir TEXT NOT NULL,
  `index` INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_producto_media_producto
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ruta (
  id_ruta CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  id_comunidad INT NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT NULL,
  duracion VARCHAR(120) NULL,
  distancia VARCHAR(120) NULL,
  dificultad VARCHAR(50) NOT NULL DEFAULT 'Media',
  tipo_experiencia TEXT NULL,
  portada_dir TEXT NULL,
  visibilidad TINYINT(1) NOT NULL DEFAULT 1,
  fecha_registro DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ruta_comunidad
    FOREIGN KEY (id_comunidad) REFERENCES comunidad(id_comunidad)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ruta_media (
  id_ruta_media CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  id_ruta CHAR(36) NOT NULL,
  media_dir TEXT NOT NULL,
  `index` INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ruta_media_ruta
    FOREIGN KEY (id_ruta) REFERENCES ruta(id_ruta)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
