import { createElement } from 'react'
import {
  Building2,
  Briefcase,
  Compass,
  FileText,
  Handshake,
  LayoutGrid,
  MapPin,
  ShieldCheck,
  Sparkles,
  UserCircle2,
  Users,
} from 'lucide-react'
import type { SectionDefinition } from '../types'
import { formatCurrency, formatDate } from './utils'

// Configuración central de las secciones del panel para que sea fácil extender CRUDs y formularios.
export const sections: SectionDefinition[] = [
  {
    key: 'monitoring',
    label: 'Monitoreo',
    endpoint: '/api/monitoring/comunidades',
    description: 'Madurez de marca y perfil comunitario.',
    icon: LayoutGrid,
    entityIdKey: 'id_comunidad',
    columns: [
      { key: 'nombre', label: 'Comunidad' },
      { key: 'municipio', label: 'Municipio' },
      { key: 'departamento', label: 'Departamento' },
      { key: 'maturity_score', label: 'Madurez' },
    ],
    formFields: [],
    emptyMessage: 'No hay comunidades para monitorear.',
  },
  {
    key: 'roles',
    label: 'Roles',
    endpoint: '/api/roles',
    description: 'Roles del sistema administrativo.',
    icon: ShieldCheck,
    entityIdKey: 'id_rol',
    columns: [
      { key: 'id_rol', label: 'ID' },
      { key: 'nombre', label: 'Nombre' },
    ],
    formFields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
    ],
  },
  {
    key: 'tipos',
    label: 'Tipos de producto',
    endpoint: '/api/tipos-producto',
    description: 'Clasificación de productos.',
    icon: Briefcase,
    entityIdKey: 'id_tipo_producto',
    columns: [
      { key: 'id_tipo_producto', label: 'ID' },
      { key: 'nombre', label: 'Nombre' },
    ],
    formFields: [{ key: 'nombre', label: 'Nombre', type: 'text', required: true }],
  },
  {
    key: 'departamentos',
    label: 'Departamentos',
    endpoint: '/api/departamentos',
    description: 'Territorio institucional.',
    icon: MapPin,
    entityIdKey: 'id_departamento',
    columns: [
      { key: 'id_departamento', label: 'ID' },
      { key: 'nombre', label: 'Nombre' },
    ],
    formFields: [{ key: 'nombre', label: 'Nombre', type: 'text', required: true }],
  },
  {
    key: 'municipios',
    label: 'Municipios',
    endpoint: '/api/municipios',
    description: 'Municipios por departamento.',
    icon: Compass,
    entityIdKey: 'id_municipio',
    columns: [
      { key: 'id_municipio', label: 'ID' },
      { key: 'nombre', label: 'Nombre' },
      { key: 'departamento', label: 'Departamento' },
    ],
    formFields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'id_departamento', label: 'Departamento', type: 'select', required: true, optionSource: '/api/departamentos' },
    ],
  },
  {
    key: 'comunidades',
    label: 'Comunidades',
    endpoint: '/api/comunidades',
    description: 'Comunidades visibles y registradas.',
    icon: Building2,
    entityIdKey: 'id_comunidad',
    columns: [
      { key: 'nombre', label: 'Comunidad' },
      { key: 'municipio', label: 'Municipio' },
      { key: 'numero_contacto', label: 'Contacto' },
      { key: 'visibilidad', label: 'Visibilidad', render: (row) => {
          return createElement('span', {
            className: row.visibilidad ? 'pill checked' : 'pill cancel',
            style: { },
          })
        }, },
    ],
    formFields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'id_municipio', label: 'Municipio', type: 'select', required: true, optionSource: '/api/municipios' },
      { key: 'descripcion', label: 'Descripción', type: 'textarea' },
      { key: 'direccion', label: 'Dirección', type: 'text' },
      { key: 'numero_contacto', label: 'Número de contacto', type: 'text' },
      { key: 'fecha_fundacion', label: 'Fecha de fundación', type: 'date', required: false },
      { key: 'visibilidad', label: 'Visible', type: 'checkbox', defaultValue: true },
      { key: 'media', label: 'Recursos', type: 'media', nestedEndpoint: '/api/comunidades', nestedCollectionKey: 'media', nestedListKey: 'id_comunidad_media', allowUpload: true, allowUrl: true, allowExisting: true, existingSource: '/api/comunidades/uploads' },
      { key: 'redes', label: 'Redes sociales', type: 'subcrud', nestedEndpoint: '/api/comunidades', nestedCollectionKey: 'redes', nestedListKey: 'id_red_comunidad', nestedFields: [
        { key: 'red_social', label: 'Red social', type: 'text', required: true },
        { key: 'usuario', label: 'Usuario', type: 'text' },
        { key: 'link', label: 'Enlace', type: 'text' },
      ], existingSource: '/api/comunidades/{id_comunidad}/redes' },
    ],
  },
  {
    key: 'asociaciones',
    label: 'Asociaciones',
    endpoint: '/api/asociaciones',
    description: 'Organizaciones, comunidades vinculadas y representantes.',
    icon: Handshake,
    entityIdKey: 'id_asociacion',
    columns: [
      { key: 'nombre', label: 'Asociación' },
      { key: 'acronimo', label: 'Acrónimo' },
      { key: 'telefono', label: 'Teléfono' },
      { key: 'comunidades_count', label: 'Comunidades' },
      { key: 'representantes_count', label: 'Representantes' },
      { key: 'visibilidad', label: 'Visible', render: (row) => (row.visibilidad ? 'Sí' : 'No') },
    ],
    formFields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'acronimo', label: 'Acrónimo', type: 'text' },
      { key: 'telefono', label: 'Teléfono', type: 'text' },
      { key: 'correo', label: 'Correo', type: 'text' },
      { key: 'logo_dir', label: 'Logo', type: 'media', allowUpload: true, allowUrl: true, allowExisting: true, existingSource: '/api/asociaciones/uploads', uploadEndpoint: '/api/asociaciones/upload' },
      { key: 'descripcion', label: 'Descripción', type: 'textarea' },
      { key: 'nombre_representante_sena', label: 'Representante SENA', type: 'text' },
      { key: 'telefono_representante_sena', label: 'Teléfono representante SENA', type: 'text' },
      { key: 'correo_representante_sena', label: 'Correo representante SENA', type: 'text' },
      { key: 'visibilidad', label: 'Visible', type: 'checkbox', defaultValue: true },
      { key: 'comunidades', label: 'Comunidades vinculadas', type: 'subcrud', nestedEndpoint: '/api/asociaciones', nestedCollectionKey: 'comunidades', nestedListKey: 'id_asociacion_comunidad', nestedFields: [
        { key: 'id_comunidad', label: 'Comunidad', type: 'select', required: true, optionSource: '/api/comunidades' },
      ] },
      { key: 'representantes', label: 'Representantes', type: 'subcrud', nestedEndpoint: '/api/asociaciones', nestedCollectionKey: 'representantes', nestedListKey: 'id_miembro_representante', nestedFields: [
        { key: 'id_miembro', label: 'Miembro', type: 'select', required: true, optionSource: '/api/miembros' },
      ] },
      { key: 'redes', label: 'Redes sociales', type: 'subcrud', nestedEndpoint: '/api/asociaciones', nestedCollectionKey: 'redes', nestedListKey: 'id_red_asociacion', nestedFields: [
        { key: 'red_social', label: 'Red social', type: 'text', required: true },
        { key: 'usuario', label: 'Usuario', type: 'text' },
        { key: 'link', label: 'Enlace', type: 'text' },
      ] },
    ],
  },
  {
    key: 'miembros',
    label: 'Miembros',
    endpoint: '/api/miembros',
    description: 'Personas asociadas a comunidades.',
    icon: Users,
    entityIdKey: 'id_miembro',
    columns: [
      {
        key: 'avatar_dir',
        label: 'Avatar',
        render: (row) => {
          const src = String(row.avatar_dir ?? '')
          return src ? createElement('img', {
            src,
            alt: 'Avatar',
            style: { width: 32, height: 32, borderRadius: '999px', objectFit: 'cover' },
          }) : '—'
        },
      },
      { key: 'nombres', label: 'Nombre' },
      { key: 'comunidad', label: 'Comunidad' },
      { key: 'rol', label: 'Rol' },
      { key: 'status', label: 'Estado' },
    ],
    formFields: [
      { key: 'nombres', label: 'Nombres', type: 'text', required: true },
      { key: 'cedula', label: 'Cédula', type: 'number', required: true },
      { key: 'id_comunidad', label: 'Comunidad', type: 'select', required: true, optionSource: '/api/comunidades' },
      { key: 'rol_id', label: 'Rol', type: 'select', required: true, optionSource: '/api/roles' },
      { key: 'avatar_dir', label: 'Avatar', type: 'media', allowUpload: true, allowUrl: false, allowExisting: false, uploadEndpoint: '/api/miembros/upload' },
      { key: 'fecha_nacimiento', label: 'Fecha de nacimiento', type: 'date' },
      { key: 'genero', label: 'Género', type: 'text' },
      { key: 'numero_contacto', label: 'Número de contacto', type: 'text' },
      { key: 'status', label: 'Estado', type: 'select', defaultValue: 'activo', options: [
        { value: 'activo', label: 'Activo' },
        { value: 'inactivo', label: 'Inactivo' },
      ] },
    ],
  },
  {
    key: 'admins',
    label: 'Administradores',
    endpoint: '/api/admins',
    description: 'Usuarios internos del panel.',
    icon: UserCircle2,
    entityIdKey: 'id_admin',
    columns: [
      { key: 'id_admin', label: 'ID' },
      { key: 'username', label: 'Usuario' },
      { key: 'active', label: 'Activo', render: (row) => (row.active ? 'Sí' : 'No') },
    ],
    formFields: [
      { key: 'username', label: 'Usuario', type: 'text', required: true },
      { key: 'password', label: 'Contraseña', type: 'password', required: true },
      { key: 'active', label: 'Activo', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    key: 'productos',
    label: 'Productos',
    endpoint: '/api/productos',
    description: 'Inventario y visibilidad.',
    icon: Briefcase,
    entityIdKey: 'id_producto',
    columns: [
      { key: 'nombre', label: 'Producto' },
      { key: 'tipo_producto', label: 'Tipo' },
      { key: 'miembro', label: 'Miembro' },
      { key: 'precio', label: 'Precio', render: (row) => formatCurrency(row.precio) },
      { key: 'visibilidad', label: 'Visible', render: (row) => (row.visibilidad ? 'Sí' : 'No') },
    ],
    formFields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'precio', label: 'Precio', type: 'number', required: true },
      { key: 'id_miembro', label: 'Miembro', type: 'select', required: true, optionSource: '/api/miembros' },
      { key: 'id_tipo_producto', label: 'Tipo de producto', type: 'select', required: true, optionSource: '/api/tipos-producto' },
      { key: 'descripcion', label: 'Descripción', type: 'textarea' },
      { key: 'recursos', label: 'Recursos', type: 'media', nestedEndpoint: '/api/productos', nestedCollectionKey: 'media', nestedListKey: 'id_producto_media', allowUpload: true, allowUrl: true, allowExisting: true, existingSource: '/api/productos/uploads' },
      { key: 'visibilidad', label: 'Visible', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    key: 'rutas',
    label: 'Rutas',
    endpoint: '/api/rutas',
    description: 'Rutas de turismo comunitario.',
    icon: Compass,
    entityIdKey: 'id_ruta',
    columns: [
      { key: 'nombre', label: 'Ruta' },
      { key: 'comunidad', label: 'Comunidad' },
      { key: 'duracion', label: 'Duración' },
      { key: 'dificultad', label: 'Dificultad' },
    ],
    formFields: [
      { key: 'nombre', label: 'Nombre', type: 'text', required: true },
      { key: 'id_comunidad', label: 'Comunidad', type: 'select', required: true, optionSource: '/api/comunidades' },
      { key: 'descripcion', label: 'Descripción', type: 'textarea' },
      { key: 'duracion', label: 'Duración', type: 'text' },
      { key: 'distancia', label: 'Distancia', type: 'text' },
      { key: 'dificultad', label: 'Dificultad', type: 'text' },
      { key: 'tipo_experiencia', label: 'Tipo de experiencia', type: 'text' },
      { key: 'visibilidad', label: 'Visible', type: 'checkbox', defaultValue: true },
      { key: 'fecha_registro', label: 'Fecha de registro', type: 'date' },
    ],
  },
  {
    key: 'categorias',
    label: 'Categorías turísticas',
    endpoint: '/api/categorias-turisticas',
    description: 'Etiquetas para el turismo.',
    icon: Sparkles,
    entityIdKey: 'id_categoria_turistica',
    columns: [
      { key: 'id_categoria_turistica', label: 'ID' },
      { key: 'nombre', label: 'Nombre' },
    ],
    formFields: [{ key: 'nombre', label: 'Nombre', type: 'text', required: true }],
  },
  {
    key: 'posts',
    label: 'Posts',
    endpoint: '/api/posts',
    description: 'Contenido publicado por la comunidad.',
    icon: FileText,
    entityIdKey: 'id_post',
    columns: [
      { key: 'miembro', label: 'Miembro' },
      { key: 'comunidad', label: 'Comunidad' },
      { key: 'descripcion', label: 'Descripción' },
      { key: 'likes', label: 'Likes' },
    ],
    formFields: [
      { key: 'id_miembro', label: 'Miembro', type: 'select', required: true, optionSource: '/api/miembros' },
      { key: 'descripcion', label: 'Descripción', type: 'textarea', required: true },
      { key: 'recursos', label: 'Recursos del post', type: 'media', nestedEndpoint: '/api/posts', nestedCollectionKey: 'media', nestedListKey: 'id_post_media', allowUpload: true, allowUrl: true, allowExisting: true, existingSource: '/api/posts/uploads' },
      { key: 'visibilidad', label: 'Visible', type: 'checkbox', defaultValue: true },
      { key: 'likes', label: 'Likes', type: 'number' },
    ],
  },
]
